### ISSUE TITLE
RSA support?

### ISSUE THREAD

**Issue by bradisbell** [erdtman/cose-js#21]
I'm curious if there are plans to support any form of asymmetric algorithm with this library.

**Comment by erdtman** [comment]
Yes. For signing I do have support for elliptic curves. RSA as you mention in the headline is a bit of another question since there is not any defined for RSA in COSE yet (a draft exists and should not be that hard).

I have started to look at ECDH for encryption but have not gotten the time to put all the pieces together.

**Comment by letmaik** [comment]
Any update on this? What would it take to implement RSA support?

**Comment by JesusMcCloud** [comment]
We have implemented RSA-PSS signature verification in a fork (including cose-wg testcases): https://github.com/JesusMcCloud/cose-js
Implementing signature creation should be straight-forward.
I'm hesitant to submit a PR, since we also added support for synchronous signature verification (without removing the promise-based call)

**Comment by letmaik** [comment]
@JesusMcCloud I'm also interested in a sync interface but probably it should be done in a separate PR. Is there any reason why you didn't use Node's crypto module for RSA-PSS? cose-js already has a dependency on it so it should be fine to use it.

**Comment by JesusMcCloud** [comment]
@letmaik we needed something that works without promises (and in the browser)

**Comment by erdtman** [comment]
@JesusMcCloud  I would be happy to review a PR

**Comment by erdtman** [comment]
the PR has been merged and released

**Comment by JesusMcCloud** [comment]
Just to clarify, this does not provide RSASSA-PSS as mentioned in the draft on RSA support in COSE https://tools.ietf.org/id/draft-jones-cose-rsa-05.html
