### ISSUE TITLE
Impement with the new WebCrypto API

### ISSUE THREAD

**Issue by jimsch** [erdtman/cose-js#22]
Except for the fact that not algorithms are supported, using the new API would seem to be a bonus.

**Comment by erdtman** [comment]
I once a upon a time looked into the WebCrypto API for this project but at that point the there was no implementation from node.js and I wanted it to be a server implementation at that point in time.

Much might have happened since then. If there is a good WebCrypto implementation for node.js then I would love to transition to it because it has been all but straight forward to implement on the node crypto library. (the minor experience I have with WebCrypto was very nice)

I´m very open to good suggestions, it has been a while since I worked on this but I have the intention to continue.

**Comment by jimsch** [comment]
https://github.com/PeculiarVentures/node-webcrypto-ossl I think does this.

**Comment by mancioshell** [comment]
I have create a pull request trying to make this module environment agnostic (doesn't matter if is run in NodeJS or in a browser)

@erdtman could you give it a look?

**Comment by mancioshell** [comment]
@erdtman is this repo maintained yet?

**Comment by erdtman** [comment]
I do not spend much time maintaining this library at the moment, but I do intend to have a look at this within the next week.

**Comment by lab-incert** [comment]
Hi there, I also had to implement a mobile app based on Ionic (Webview) to check the signature of DGC.

So I replaced the dependencies to node modules (cbor, crypto) and adapt the code to be able to use it in browsers:
https://github.com/ehn-digital-green-development/dgc-check-mobile-app/blob/main/src/app/cose-js/sign.js

**Comment by mancioshell** [comment]
> Hi there, I also had to implement a mobile app based on Ionic (Webview) to check the signature of DGC.
> 
> So I replaced the dependencies to node modules (cbor, crypto) and adapt the code to be able to use it in browsers:
> https://github.com/ehn-digital-green-development/dgc-check-mobile-app/blob/main/src/app/cose-js/sign.js

I think `cbor-js` does not have the same methods of `cbor`. For example `cose-js` use encodeCanonical method which does not exist in cbor-js npm module.
Furthermore, cbor have a package ready for the web: [cbor-web](https://github.com/hildjj/node-cbor/tree/main/packages/cbor-web). Maybe i could integrate it in my PR.

**Comment by erdtman** [comment]
@mancioshell just merged your PR, if you would also look at the cbor issue that would be great.

**Comment by lovasoa** [comment]
I have started working on a port to typescript and webcrypto in https://github.com/lovasoa/cosette

**Comment by lovasoa** [comment]
If someone is interested, I published my version to npm: https://www.npmjs.com/package/cosette
It already finished porting all the signing logic to webcrypto, so it is already usable for Checking Digital Green Certificates.
