### ISSUE TITLE
What is the expected shape of the verifier.key argument in cose.verify ?

### ISSUE THREAD

**Issue by lovasoa** [erdtman/cose-js#46]
Given the examples in the README and the code itself, it [looks like](https://github.com/erdtman/cose-js/blob/master/lib/sign.js#L219) `cose.sign.verify` expects its second argument's type to look something like

```ts
interface Verifer {
  externalAAD?: Buffer,
  key: {
    x: Buffer,
    y: Buffer,
    kid?: string,
  },
}
```

Except that in 
https://github.com/erdtman/cose-js/blob/master/lib/sign.js#L157 , `verifier.key` is passed directly to node's `Verify.very` which [does not expect an input object that looks like that](https://nodejs.org/api/crypto.html#crypto_verify_verify_object_signature_signatureencoding)

**Comment by erdtman** [comment]
Sorry for the veeeeery long delay in answering.

The code has changed slightly since May so I guess it is this line you are looking at https://github.com/erdtman/cose-js/blob/6e4a381c5c96391d9f9f0b13d2802243fe609197/lib/sign.js#L182

It is used for RSA signatures, not he prettiest solution so I should likely refactor it a bit when I have time. See  https://github.com/erdtman/cose-js/blob/master/test/rsa-pkcs-examples.js for an example of how it is used.
