### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by MillaSense** [erdtman/cose-js#58]
Hey there.. Maybe i can't find that fault in my code, but i'm getting an error:

```
Failed to compile.
./node_modules/cose-js/node_modules/cbor/lib/utils.js
Module not found: Error: Can't resolve 'node-inspect-extracted' in '..\node_modules\cose-js\node_modules\cbor\lib'
```
in utils.js > try/catch for variable util > line 22: 
  util = require('node-inspect-extracted')

..sitting way to long before my screens, but.. sorry: can't find it, all i tried was
` await cose.sign.verify(COSEMessage, verifier); `

installed version is: -- cose-js@0.8.2

..and have a wonderful christmas! ;-)

**Comment by erdtman** [comment]
I cannot say exactly what is wrong but to shake up things a bit I created a new release with updated dependencies.
so if you could test to delete your node_modules folder and then re-install dependencies and see if that helps.

Another thing to try out, have you tested to clone my cose-js library and run the tests (if that works it would to me suggest that your issue is local to your project).

Is your code public then I could also try to clone and build it.

**Comment by MillaSense** [comment]
Gosh.. Thank you so very much!

After doing so the real missing
package  `node-inspect-extracted`
threw an error - fixed that!

..happy new year!

**Comment by erdtman** [comment]
Good to hear
